set search_path = "CSI2132 Project";

insert into movie(movie_id, name, date_released, language, country) values (100,'The Shawshank Redemption', '1994-10-14', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (101,'The Godfather', '1972-03-24', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (102,'The Godfather: Part II', '1974-12-20', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (103,'The Dark Knight', '2008-07-18', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (104,'Schindler''s List', '1992-02-04', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (105,'12 Angry Men', '1957-04-01', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (106,'Pulp Fiction', '1994-10-14', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (107,'The Lord of the Rings: The Return of the King', '2003-12-17', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (108,'The Good, the Bad, and the Ugly', '1967-12-29', 'Italian', 'Italy');
insert into movie(movie_id, name, date_released, language, country) values (109,'Fight Club', '1999-10-15', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (110,'The Lord of the Rings: The Fellowship of the Ring', '2001-12-19', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (111,'Star Wars: Episode V - The Empire Strikes Back', '1980-06-20', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (112,'Forrest Gump', '1994-07-06', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (113,'Inception', '2010-07-16', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (114,'The Lord of the Rings: The Two Towers', '2002-12-18', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (115,'One Flew Over the Cuckoo''s Nest', '1975-11-21', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (116,'Goodfellas', '1990-09-21', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (117,'The Matrix', '1999-03-31', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (118,'Seven Samurai', '1956-11-19', 'Japanese', 'Japan');
insert into movie(movie_id, name, date_released, language, country) values (119,'Star Wars: Episode IV - A New Hope', '1977-05-25', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (120,'City of God', '2004-02-13', 'Portuguese', 'Brazil');
insert into movie(movie_id, name, date_released, language, country) values (121,'Se7en', '1995-09-22', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (122,'The Silence of the Lambs', '1991-02-14', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (123,'It''s a Wonderful Life', '1947-01-07', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (124,'The Usual Suspects', '1995-09-15', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (125,'Life is Beautiful', '1999-02-12', 'Italian', 'Italy');
insert into movie(movie_id, name, date_released, language, country) values (126,'Léon: The Professional', '1994-11-18', 'English', 'France');
insert into movie(movie_id, name, date_released, language, country) values (127,'Once Upon a Time in the West', '1969-07-04', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (128,'Spirited Away', '2003-03-28', 'Japanese', 'Japan');
insert into movie(movie_id, name, date_released, language, country) values (129,'Saving Private Ryan', '1998-07-24', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (130,'Interstellar', '2014-11-07', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (131,'Casablanca', '1943-01-23', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (132,'American History X', '1998-11-20', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (133,'City Lights', '1931-03-07', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (134,'Psycho', '1960-09-08', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (135,'Raiders of the Lost Ark', '1981-06-12', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (136,'Rear Window', '1954-08-01', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (137,'The Intouchables', '2011-11-02', 'French', 'France');
insert into movie(movie_id, name, date_released, language, country) values (138,'Modern Times', '1936-02-25', 'English', 'USA');
insert into movie(movie_id, name, date_released, language, country) values (139,'The Green Mile', '1999-12-10', 'English', 'USA');