set search_path = "CSI2132 Project";

insert into Studio(studio_id, name, country) values(100,'Castle Rock Entertainment','USA');
insert into Studio(studio_id, name, country) values(101,'Paramount Pictures','USA');
insert into Studio(studio_id, name, country) values(102,'Alfran Productions','USA');
insert into Studio(studio_id, name, country) values(103,'The Coppola Company','USA');
insert into Studio(studio_id, name, country) values(104,'Warner Bros.','USA');
insert into Studio(studio_id, name, country) values(105,'Legendary Pictures','USA');
insert into Studio(studio_id, name, country) values(106,'Syncopy','UK');
insert into Studio(studio_id, name, country) values(107,'DC Comics','USA');
insert into Studio(studio_id, name, country) values(108,'Universal Pictures','USA');
insert into Studio(studio_id, name, country) values(109,'Amblin Entertainment','USA');
insert into Studio(studio_id, name, country) values(110,'Orion-Nova Productions','USA');
insert into Studio(studio_id, name, country) values(111,'Miramax','USA');
insert into Studio(studio_id, name, country) values(112,'A Band Apart','USA');
insert into Studio(studio_id, name, country) values(113,'Jersey Films','USA');
insert into Studio(studio_id, name, country) values(114,'New Line Cinema','USA');
insert into Studio(studio_id, name, country) values(115,'WingNut Films','New Zealand');
insert into Studio(studio_id, name, country) values(116,'The Saul Zaentz Company','USA');
insert into Studio(studio_id, name, country) values(117,'Produzioni Europee Associati (PEA)','Italy');
insert into Studio(studio_id, name, country) values(118,'Arturo González Producciones Cinematográficas, S.A','Spain');
insert into Studio(studio_id, name, country) values(119,'Constantin Film Produktion','Germany');
insert into Studio(studio_id, name, country) values(120,'United Artists','USA');
insert into Studio(studio_id, name, country) values(121,'Fox 2000 Pictures','USA');
insert into Studio(studio_id, name, country) values(122,'Regency Enterprises','USA');
insert into Studio(studio_id, name, country) values(123,'Linson Films','USA');
insert into Studio(studio_id, name, country) values(124,'LucasFilm','USA');
insert into Studio(studio_id, name, country) values(125,'Fantasy Films','USA');
insert into Studio(studio_id, name, country) values(126,'Village Roadshow Pictures','USA');
insert into Studio(studio_id, name, country) values(127,'Groucho II Film Partnership','USA');
insert into Studio(studio_id, name, country) values(128,'Toho Company','Japan');
insert into Studio(studio_id, name, country) values(129,'20th Century Fox Film Corporation','USA');
insert into Studio(studio_id, name, country) values(130,'02 Films','Brazil');
insert into Studio(studio_id, name, country) values(131,'VideoFilmes','Brazil');
insert into Studio(studio_id, name, country) values(132,'Globo Filmes','Brazil');
insert into Studio(studio_id, name, country) values(133,'Cecchi Gori Pictures','USA');
insert into Studio(studio_id, name, country) values(134,'Juno Pix','USA');
insert into Studio(studio_id, name, country) values(135,'Strong Heart/Demme Production','USA');
insert into Studio(studio_id, name, country) values(136,'Orion Pictures','USA');
insert into Studio(studio_id, name, country) values(137,'Liberty Films','USA');
insert into Studio(studio_id, name, country) values(138,'PolyGram Filmed Entertainment','UK');
insert into Studio(studio_id, name, country) values(139,'Spelling Films International',null);
insert into Studio(studio_id, name, country) values(140,'Blue Parrot','USA');
insert into Studio(studio_id, name, country) values(141,'Melampo Cinematografica','Italy');
insert into Studio(studio_id, name, country) values(142,'Cecchi Gori Group Tiger Cinematografica','Italy');
insert into Studio(studio_id, name, country) values(143,'Gaumont','France');
insert into Studio(studio_id, name, country) values(144,'Les Films du Dauphin','France');
insert into Studio(studio_id, name, country) values(145,'Rafran Cinematografica','Italy');
insert into Studio(studio_id, name, country) values(146,'Finanzia San Marco',null);
insert into Studio(studio_id, name, country) values(147,'Tokuma Shoten','Japan');
insert into Studio(studio_id, name, country) values(148,'Studio Ghibli','Japan');
insert into Studio(studio_id, name, country) values(149,'Nippon Television Network','Japan');
insert into Studio(studio_id, name, country) values(150,'DreamWorks SKG','USA');
insert into Studio(studio_id, name, country) values(151,'Savoy Pictures','USA');
insert into Studio(studio_id, name, country) values(152,'The Turman-Morrissey Company','USA');
insert into Studio(studio_id, name, country) values(153,'Charles Chaplin Productions','USA');
insert into Studio(studio_id, name, country) values(154,'Shamley Productions','USA');
insert into Studio(studio_id, name, country) values(155,'Patron Inc.',null);
insert into Studio(studio_id, name, country) values(156,'Quad Productions','France');
insert into Studio(studio_id, name, country) values(157,'Ten Films','France');
insert into Studio(studio_id, name, country) values(158,'Canal+','France');
insert into Studio(studio_id, name, country) values(159,'Darkwoods Productions','USA');